name = "libsap"
description = "Asynchronous message-passing for protocol stacks"
version = "0.1.0-dev"

authors = ["Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[build-switches]
"*".Ada_Version = "Ada2022"

[configuration.variables]
Tasking_Supported = { type = "Boolean", default = true }